events { }

http {
    # Cria uma zona de memória para o Rate Limit (limite de 2 requisições por segundo)
    limit_req_zone $binary_remote_addr zone=limite_basico:10m rate=2r/s;

    server {
        listen 80;

        # Serve o front-end visual na rota raiz
        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        # Rota de Usuários protegida
        location /usuarios {
            limit_req zone=limite_basico burst=5 nodelay;
            proxy_pass http://servico-usuarios:5000;
        }

        # Rota de Produtos protegida
        location /produtos {
            limit_req zone=limite_basico burst=5 nodelay;
            proxy_pass http://servico-produtos:5000;
        }

        # Mensagem customizada para quando o Nginx bloquear o ataque
        error_page 503 /503.html;
        location = /503.html {
            return 503 '{"erro": "Protecao ativada! Muitas requisicoes por segundo."}';
            default_type application/json;
        }
    }
}